INHERIT: mkdocs.maybe-insiders.yml
site_name: Chinese Docs
site_description: Chinese learning notes for pinyin, vocabulary, grammar, speaking, and class sessions
site_url: https://ricardotran92.github.io/chinese-docs/
use_directory_urls: false # To get img locations easily

theme:
  name: material
  custom_dir: overrides
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - layout.wide
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

repo_name: ricardotran92/docs
repo_url: https://github.com/ricardotran92/docs

plugins:
  search: null
  macros:
    include_yaml:
    - en/data/external_links.yml
    - en/data/github_sponsors.yml
    - en/data/people.yml
    - en/data/contributors.yml
    - en/data/translators.yml
    - en/data/translation_reviewers.yml
    - en/data/skip_users.yml
    - en/data/members.yml
    - en/data/sponsors_badge.yml
    - en/data/sponsors.yml
    - en/data/topic_repos.yml
  mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_typingdoc
          - pymdownx.arithmatex
          show_root_heading: true
          show_if_no_docstring: true
          preload_modules:
          - httpx
          - starlette
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          generic: true

nav:
- Home: index.md
- Speaking:
  - IPA guide: speaking/ipa-guide.md
- Pinyin:
  - 01. Giới thiệu về phiên âm: pinyin/01-gioithieuvephienam.md
  - 02. Thanh điệu: pinyin/02-thanhdieu.md
  - 03. Thanh mẫu: pinyin/03-thanhmau.md
  - 04. Vận mẫu: pinyin/04-vanmau.md

- Vocabulary:
  - L1-1. Giới thiệu bản thân: vocabulary/L1-1-gioi_thieu_ban_than.md
  - L1-2. Hỏi về nghề nghiệp: vocabulary/L1-2-hoi_ve_nghe_nghiep.md
  - L1-3. Quốc tịch: vocabulary/L1-3-quoc_tich.md
  - L1-4.1. Thành viên trong gia đình: vocabulary/L1-4.1-thanh_vien_trong_gia_dinh.md
  - L1-4.2. Thành viên trong gia đình: vocabulary/L1-4.2-thanh_vien_trong_gia_dinh.md
  - L1-5. Khả năng ngôn ngữ: vocabulary/L1-5-kha_nang_ngon_ngu.md
  - L1-6.1. Hôm nay là ngày mùng 1: vocabulary/L1-6.1-hom_nay_la_ngay_mung_1.md
  - L1-6.2. Hôm nay là ngày mùng 1: vocabulary/L1-6.2-hom_nay_la_ngay_mung_1.md
  - L1-7.1. Sinh nhật: vocabulary/L1-7.1-sinh_nhat.md
  - L1-7.2. Sinh nhật: vocabulary/L1-7.2-sinh_nhat.md
  - L1-8.1. Kế hoạch cuối tuần: vocabulary/L1-8.1-ke_hoach_cuoi_tuan.md

- Grammar:
  - L1-1. Giới thiệu bản thân: grammar/L1-1-gioi_thieu_ban_than.md
  - L1-2. Hỏi về nghề nghiệp: grammar/L1-2-hoi_ve_nghe_nghiep.md
  - L1-3. Quốc tịch: grammar/L1-3-quoc_tich.md
  - L1-4. Thành viên trong gia đình: grammar/L1-4-thanh_vien_trong_gia_dinh.md
  - L1-5.1. Khả năng ngôn ngữ: grammar/L1-5.1-kha_nang_ngon_ngu.md
  - L1-5.2. Khả năng ngôn ngữ: grammar/L1-5.2-kha_nang_ngon_ngu.md
  - L1-5.3. Khả năng ngôn ngữ: grammar/L1-5.3-kha_nang_ngon_ngu.md
  - L1.6. Hôm nay là ngày mùng 1: grammar/L1-6-hom_nay_la_ngay_mung_1.md
  - L1-7.1. Sinh nhật: grammar/L1-7.1-sinh_nhat.md
  - L1-7.2. Sinh nhật: grammar/L1-7.2-sinh_nhat.md
  - L1-7.3. Sinh nhật: grammar/L1-7.3-sinh_nhat.md

- Main Lesson:
  - L1-1. Giới thiệu bản thân: main-lesson/L1-1-gioi_thieu_ban_than.md
  - L1-2. Hỏi về nghề nghiệp: main-lesson/L1-2-hoi_ve_nghe_nghiep.md
  - L1-3. Quốc tịch: main-lesson/L1-3-quoc_tich.md
  - L1-4. Thành viên trong gia đình: main-lesson/L1-4-thanh_vien_trong_gia_dinh.md
  - L1-5. Khả năng ngôn ngữ: main-lesson/L1-5-kha_nang_ngon_ngu.md
  - L1-6. Hôm nay là ngày mùng 1: main-lesson/L1-6-hom_nay_la_ngay_mung_1.md
  - L1-7. Sinh nhật: main-lesson/L1-7-sinh_nhat.md

- Test:
  - L1-3. Quốc tịch: test/L1-3-quoc_tich.md
  - L1-5. Khả năng ngôn ngữ: test/L1-5-kha_nang_ngon_ngu.md
  - L1-6. Hôm nay là ngày mùng 1: test/L1-6-hom_nay_la_ngay_mung_1.md
  - L1-7. Sinh nhật: test/L1-7-sinh_nhat.md

- Communication:
  - L1-1. Chữ số - 1: communication/L1-1-chu_so_1.md

- Chinese Class:
  - Day 01: chinese-class/day-01.md
  - Day 02: chinese-class/day-02.md
  
- Self-Study:
  - Proper Noun: self-study/proper-noun.md
  - Places: self-study/places.md
  - Dining: self-study/dining.md


markdown_extensions:
  abbr: null
  attr_list: null
  footnotes: null
  md_in_html: null
  tables: null
  toc:
    permalink: true
  pymdownx.betterem: null
  pymdownx.caret: null
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite: null
  pymdownx.keys: null
  pymdownx.mark: null
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.tilde: null
  pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    - info
    - check
  pymdownx.blocks.details: null
  pymdownx.blocks.tab:
    alternate_style: true
  mdx_include: null
  markdown_include_variants: null

  pymdownx.arithmatex:
    generic: true

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/ricardotran92/docs
  - icon: fontawesome/brands/discord
    link: https://discord.gg/...
  - icon: fontawesome/brands/twitter
    link: https://x.com/...
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/...
  - icon: fontawesome/solid/globe
    link: https://....com

extra_css:
- css/termynal.css
- css/custom.css

extra_javascript:
- js/termynal.js
- js/custom.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

hooks:
- scripts/mkdocs_hooks.py
